import Head from "next/head";
import styles from "../styles/Home.module.css";
import ProductComponent from "../components/ProductComponent";
import AboutComponent from "../components/AboutComponent";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Madhav Masaala</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* slider */}
      <div className={styles.slider}>
        <div className={styles.slide}>
          <span className={styles.heading}>Madhav Masaala</span>
          <p className={styles.desc}>
            Our masalas help you in enhancing the flavour & bringing
            authenticity to your dishesh
          </p>
          <button className={styles.button}>Order Now</button>
        </div>
      </div>

      {/* product */}
      <ProductComponent />
      {/* about us */}
      <AboutComponent />
      {/* tagline */}
      <div className={styles.bottom_line}>
        <p>Buy 100% original masala and spices online from Madhav Masaala.</p>
        <button>Order Now</button>
      </div>
    </div>
  );
}
